name: asiatic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^5.2.1+1
  get_storage: ^2.0.3
  package_info_plus: ^3.0.3
  zoom_tap_animation: ^1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  # flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/logo/
    - assets/images/

  uses-material-design: true
#Mohammad Khalid Bin Oalid
